#+TITLE: Oppgaver for IfI våren 2023
# +OPTIONS: toc:2          (only include two levels in TOC)
#+OPTIONS: toc:nil        (no default TOC at all)

# * Oppgaver utført høsten 2022



# p* Veiledning


* PhD veiledning
- Dette semesteret har  jeg jobbet med Farzane Karami,
  som jeg er hovedveileder for. Hun har gjort  ferdig og levert sin
  avhandling  (i mai):
  /Language-based Approaches for Enforcing Privacy and Security Policies/

- Jeg har jobbet jevnlig med Chinmayi Baramashetru. Et invitert bok-kapittel
  er sendt inn (med Chinmayi, Lizeth og meg som forfattere),
  og en annen artikkel er under arbeid, og en tredje artikkel er påbegynt.

- Jeg har jobbet videre med Hamed Arshad, som  disputerte  des. 2022,
  om publisering av arbeider som direkte bygger på dr.arbeidet hans.
** Mentoring

- Jeg har fulgt opp flere PhD studenter i 4.,
  8., 9. og 10. etg. 
# som en slags mentor. 

- Jeg har hjulpet flere  PhD kandidater med å finne jobb
  etter PhD studiet.

-  Jeg er invitert med på en artikkel med en PhD student fra ND, der
  jeg er bedt om å se på personvernsaspektet.

** PhD 3. semester evaluering for 

- Paul Kobialka (PSY/ASR), 1. juni 2023
- Poushali Sengupta (NR), 1. juni 2023
 
* Master veiledning
- Jeg har bidratt med veiledning av  master-studenter.
- Jeg har vært ansvarlig for en Erasmus utvekslings-student.
** Master sensurering
- Jeg er sensor for Thalha Khan:
  /Machine Learning and Artificial Intelligence in Malware Detection/,
  (juni 2023).
- Jeg er sensor for Sigbjørn Bjunes:
 /The Importance of Social Awareness In Norwegain Organisations/ (juni 2023)

* Publikasjoner
- /Integrating Data Privacy Compliance in Active Object Languages/.
  Chinmayi Prabhu Baramashetru, S. Lizeth Tapia Tarifa, Olaf Owe.
  Submitted as a chapter to a Spinger special issue on /Active Object
  Languages/  (May 2023).

- /XACML2mCRL2: Automatic Transformation of XACML Policies into mCRL2 Specifications/.
  Hamed Arshad, Ross Horne, Christian Johansen, Olaf Owe, Tim
  A. C. Willemse.   
  Revision submitted to *Science of Computer  Programming* (May 2023).

# Hamed semantic x2 (framework review) process alg
# : A decision has been made on SCICO-D-22-00293


** Under arbeid

- /From Ping to Pong and Back Again/.
  
   Frank S. de Boer (CWI), Einar Broch Johnsen, Olaf Owe,
   Violet Ka I Pun  (HVL),  Silvia Lizeth Tapia Tarifa.

- /A Formal Model of Language-Based GDPR in Distributed Systems/. 
  Chinmayi Prabhu Baramashetru, S. Lizeth Tapia Tarifa,
  Olaf Owe.

- /An Interpreter for  Data Privacy Compliance in an Active Object
  Language/. 
  Chinmayi P. Baramashetru, S. Lizeth Tapia Tarifa,
  Olaf Owe.


** Pris 

Følgende tidsskrifts-artikkel er nominert for en best paper award:

Olaf Owe, Elahe Fazeldehkordi: A Lightweight Approach to Smart Contracts Supporting Safety, Security, and
Privacy.  Journal of Logical and Algebraic Methods in Programming (JLAMP) Vol. 127, 100772, 2022 Elsevier 

* Reviewing
- Jeg  er reviewer for en spesial utgave 
  om språk for aktive objekter, publisert av Springer.
- Jeg er blitt med i PC komiteen for Modelsward 2024.

# * Mer detaljert oversikt over  veiledningsoppgaver
* Oversikt over videre PhD veiledning:

- Farzane Karami  (hovedveileder) disputas forventes i sept/okt  2023
- Marius Geitle  (hovedveileder) forventes ferdig i 2023/2024
- Chinmayi Prabhu Prasad Baramashetru  (medveileder) forventes ferdig
  i slutten av 2024
# ** ferdige PhD


* Prosjektarbeid
- Jeg er med på PriTEM prosjektet
# https://www.mn.uio.no/ifi/english/research/projects/pritem/index.html

- Jeg er involvert i et prosjekt med AtomIQ AS sammen med UiO Blockchain Lab.

- Jeg har hatt kontakt med miljøer ved 
  ITS, SINTEF, NR, Prosa AS, og Nvidia (Tyskland)
  om mulige fremtidige prosjekter.
* Annet 
- Jeg er med i styret av BlockChain Lab ved IfI
https://www.mn.uio.no/ifi/english/research/networks/blockchainlab/

# - Jeg er involvert i planlegging av  samarbeid mellom AtomIQ AS og  UiO
#  BlockChain Lab.
 
- Jeg  har  holdt et  foredrag om smarte kontrakter
  ved en workshop med Norges Bank i regi av BlockChain Lab.

** COMMENT Oversikt over master veiledning:
- Lea Nikoline Nøstdahl (hovedveileder) forventes ferdig i 2022
- Victoria Hyun Oh (hovedveileder) forventes ferdig i 2022
- Haakon Staff (hovedveileder) forventes ferdig i 2022
- Lara Okafor (medveileder) forventes ferdig i 2022

* COMMENT Publikasjoner
#  ** Tidss
- Hamed Arshad, Christian Johansen, Olaf Owe, Pablo Picazo-Sanchez,
  Gerardo Schneider: 
 /Semantic Attribute- Based Encryption: A Framework for Combining ABE
  schemes with Semantic Technologies./
 *Information Sciences* 2022,
  https://doi.org/10.1016/j.ins.2022.10.132
- Hamed Arshad, Christian Johansen, Olaf Owe: 
 /Semantic Attribute-Based   Access Control: A review on current
  status and future perspectives./ 
 *Journal of Syst. Archit.* 129: 102625 (2022)
- Hamed Arshad, Ross Horne, Christian Johansen, Olaf Owe, Tim
  A. C. Willemse: 
 /XACML2mCRL2: Automatic Transformation of XACML Policies into mCRL2 Specifications/,
  Submitted to *Science of Computer  Programming* as VSI: DisCoTec 2022 Artifacts, Nov. 2022.

- Hamed Arshad, Ross Horne, Christian Johansen, Olaf Owe, Tim
  A. C. Willemse: 
  /Process Algebra Can Save Lives: Static Analysis of  XACML Access Control Policies Using mCRL2/. 
  *Lecture Notes in  Computer Science*, vol 13273. FORTE 2022: 11-30, Springer, 2022
-  Chinmayi Prabhu Baramashetru, S. Lizeth Tapia Tarifa, Olaf Owe, and
   Nils Gruschka: 
 /A Policy Language to Capture  Compliance of Data Protection Requirements./
   *Lecture Notes in Computer Science*, vol 13274,
   pp. 289-309. Springer, 2022.


Software No.: SCICO-D-22-00293 
Title:  
Ross Horne ross.horne@uni.lu, "Christian Johansen" christian.johansen@ntnu.no, "Olaf Owe" olaf@ifi.uio.no, "Tim A. C. Willemse" t.a.c.willemse@tue.nl

XACML2mCRL2: Automatic Transformation of XACML Policies into mCRL2 Specifications  
Science of Computer Programming, in revision, 2023

a journal paper has been nominated for best paper award


** COMMENT Master

Sammen med andre ved BlockChain lab har jeg formulert 9 master oppgaver
(hvor flere av dem er for mer enn 1 student)
 til et trading system med en egen digital valuta.
Flere forskningsgrupper ved IfI og andre instittuer ved UiO,  samt et firma er med på dette.
Se 
https://www.mn.uio.no/ifi/english/research/networks/blockchainlab/
master-projects-connected-to-a-blockchain-based-equity-investment-and-trading-platform.pdf
Vi har hatt innledende møter med potensielle masterstudenter her.


Videre er jeg  satt opp som medveileder for master og doktorgradsstudenter
på PriTEM prosjektet.
